### ISSUE TITLE
ie10

### ISSUE THREAD

**Issue by crirus** [Pierrinho/Allofthelights.js#1]
Hello

In IE10 it pushes down my player to the same distance as player height.

Any clue when IE10 will be fully tested?

**Comment by crirus** [comment]
after some digging I see this DIV  fluid_width_video_wrapper gets a padding-top  of 55.5% and that cause IE10 to display the player way lower than desired position.

**Comment by Pierrinho** [comment]
Hello,
Sorry for wait. New 2.0 version has been tested on IE9, IE10 & IE11 and responsive player video works !
