### ISSUE TITLE
Possible conflict with fitvids.js

### ISSUE THREAD

**Issue by viktorix** [Pierrinho/Allofthelights.js#7]
I was working on implementing allofthelights.js on a site that already uses fitvids.js (http://fitvidsjs.com/), and noticed there is an issue. fitvids.js adds a DIV around video iframes with certain padding, when allofthelights.js is implemented (and works) it duplicates this specific DIV which in turn pushes video down due to double padding. See screenshot.
![js-bug](https://cloud.githubusercontent.com/assets/1692600/4100496/dac7393a-309c-11e4-920e-60efb34cf380.png)

**Comment by Pierrinho** [comment]
Allofthelights.js already implements FitVids.js by default ! You have two options. Either you use Allofthelights.js and FitVids.js separately : you must configure the parameter "is_responsive" to false in config of Allofthelights.js. Either you let Allofthelights.js makes responsive video so you can uninstall FitVids.js.
